#include "balanceoDeCargas.h"

copia* balancearCarga(int nroJob, infoDeFs* info){
	//PARA RR: A PARTIR DEL NRO DE JOB ME FIJO CUAL DE LAS DOS COPIAS ES LA QUE MENOS TRABAJO
	//PARA WRR: A PARTIR DE LAS DOS COPIAS RECORRO LA TABLA
	return NULL;
}

char* nodoParaReduccionGlobal(int nroJob){
	//PARA RR: FILTRO LAS OPERACIONES DEL JOB Y ME FIJO CUAL ES EL QUE MENOS TIENE
	//PARA WRR: FILTRO OPERACIONES DEL JOB Y A PARTIR DE LOS NODOS VOY CONTANDO EN TODA LA TABLA
	return NULL;
}
